### ISSUE TITLE
Loot, enemies and terminal codes do not show up on the minimap

### ISSUE THREAD

**Issue by CootieDwagon** [VanillaChan6571/LethalCompanyFairPlayMinimap#2]
i enabled/disabled various settings, even went into the cofig itself to enable/disable various settings to test, no matter what i did, loot, enemies and terminal codes will NOT show up on the minimp

**Comment by VanillaChan6571** [comment]
Well, first of all, Fair Play Edition removes the Loot, Enemies and Terminal Codes. So this is NOT an issue.
