### ISSUE TITLE
Version 1.0.8 doesn't seem to launch or create a config

### ISSUE THREAD

**Issue by dremaster007** [VanillaChan6571/LethalCompanyFairPlayMinimap#5]
Steps to reproduce.

1) Uninstall all versions and files from Minimap Mod
2) Install 1.0.8 and launch
3) See no config in files and mod doesn't work in game
4) Uninstall 1.0.8
5) Install 1.0.7 and launch
6) Files generate and mod works in game

**Comment by VanillaChan6571** [comment]
> Steps to reproduce.
> 
>     1. Uninstall all versions and files from Minimap Mod
> 
>     2. Install 1.0.8 and launch
> 
>     3. See no config in files and mod doesn't work in game
> 
>     4. Uninstall 1.0.8
> 
>     5. Install 1.0.7 and launch
> 
>     6. Files generate and mod works in game

Minimap-Fair-Play.cfg

**Comment by VanillaChan6571** [comment]
I will have to look on this more it seems something is wrong on v55+

**Comment by VanillaChan6571** [comment]
1.0.9 Fixes the Invalid Version Type. It should be working when Thunderstore updates itself.
